import React from "react";
import '../styles/login.css'
import styled from "@emotion/styled";
/**
 * `<Frame13>` ('Frame 13')
 * - [Open in Figma](https://figma.com/file/asUgXa0tsHsNH105i1oLCa?node-id=60:77)
 * - [Open in Grida](https://code.grida.co/files/asUgXa0tsHsNH105i1oLCa?node=60:77)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Frame13/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a117f561-36de-41dd-8a5a-5fad070a7dcb)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://asUgXa0tsHsNH105i1oLCa/60:77 -->
 */
export function Frame13({socket}) {

	
	const [login_data,setloginData] = React.useState({
		username : "",
		password : ""
	})

	function changeLoginData(e) {
		setloginData({
			...login_data,
			[e.target.name] : e.target.value
		})
		console.log(login_data)
	}



	React.useEffect(()=>{
		socket.on("login",(status)=>{
			if (status=== "successfull") {
				alert("login successfull")
				window.location.href = '/'
			}
			else {
				alert("incorrect username or password")
			}
		})
		return ()=>{
			socket.off("login")
		}
	},[socket])


  return (
    <RootWrapperFrame13>
      <Frame10>
        <ChrisLiveraniHujDz6CjEaMUnsplash1/>
        <CloudCar>
          CloudCar
        </CloudCar>
        <LogIn>
          Log in
        </LogIn>
        <Email>
          Email
        </Email>
        <Password>
          Password
        </Password>
        <Group27/>
        <Group24>
          {/* <Rectangle16/> */}
          {/* <EnterEmailHere>
            Enter email here
          </EnterEmailHere> */}
            <input
            type="text"
            placeholder="Enter username here"
            // Add CSS classes for styling
            className="message-input-container"
			name="username"
			onChange={changeLoginData}
            />
        </Group24>
        <Group28>
          {/* <Rectangle16/> */}
          {/* <EnterPasswordHere>
            Enter password here
          </EnterPasswordHere> */}
            <input
            type="text"
            placeholder="Enter password here"
            // Add CSS classes for styling
            className="message-input-container"
			name = "password"
			onChange={changeLoginData}
            />
        </Group28>
        <Rectangle19/>
        <Group26 onClick={()=>{socket.emit("login",login_data)}}>
          <Group29>
            <Rectangle18/>
            <Login>
              Login
            </Login>
          </Group29>
        </Group26>
        <IForgotMyPassword>
          I forgot my password
        </IForgotMyPassword>
        <DonTHaveAnAccountSignUp>
          Don’t have an account? <div style={{cursor:"pointer"}} onClick={()=>{window.location.href = "/signup"}}>Sign up</div>
        </DonTHaveAnAccountSignUp>
      </Frame10>
    </RootWrapperFrame13>
  )
}


const RootWrapperFrame13 = styled.div`
	min-height: 100vh;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const Frame10 = styled.div`
	width: 1440px;
	height: 832px;
	overflow: hidden;
	background: linear-gradient(-180deg, rgb(26, 44, 46), black);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: calc((calc((50% + 0px)) - 720px));
	top: 0px;
`;

const ChrisLiveraniHujDz6CjEaMUnsplash1 = styled.div`
	width: 970px;
	height: 832px;
	background: url(https://s3-alpha-sig.figma.com/img/5e8d/8d05/bfc0904f0822d9707a84ec0578dcac16?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=U~TXOwYY6g~XAQpJ7evSxfHeg1f1Th1EpCaVeW8dyIjnWY8Hf3Hd~JS3~XSiUZH0iNXOgBensMhTkD~8yXJXOyi~Y8iPfU9y0SYIgGD~qUzKHk7RczuBNaIBjxmiB2GxOsbZXTIqpDGT6buc6KunW5mQyvFyOyP~VYJ2K8TKkfCPt3uSZwPoCnMyGgTZ7PdNVCLPxtqNQLhQ2NUBGskNh8DQ7NeALuw8n2N-dAv5QAbjN-jQn2CgUelu9hBE4QNiDLf1wZFdU5ipw9uFg-3lJNFZqdj6gpfyzLxfTYTQBashWwo6iag~V5VDXOIQYy8ROQoWJTl6FQJgO0SEjzWPeA__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const CloudCar = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 40px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 172px;
	min-height: 32px;
	position: absolute;
	left: calc((calc((50% + 480px)) - 86px));
	top: calc((calc((50% + -213px)) - 16px));
	height: 32px;
`;

const LogIn = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 66px;
	min-height: 24px;
	position: absolute;
	left: 1174px;
	top: 275px;
	height: 24px;
`;

const Email = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 44px;
	min-height: 18px;
	position: absolute;
	left: 1024px;
	top: 337px;
	height: 18px;
`;

const Password = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 73px;
	min-height: 18px;
	position: absolute;
	left: 1024px;
	top: 427px;
	height: 18px;
`;

const Group27 = styled.div`
	position: absolute;
	left: 1025px;
	top: 515px;
`;

const Group24 = styled.div`
	width: 381px;
	height: 41px;
	position: absolute;
	left: 1010px;
	top: 365px;
`;

const Rectangle16 = styled.div`
	width: 381px;
	height: 41px;
	background: rgb(96, 89, 89);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const EnterEmailHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 211px;
	min-height: 20px;
	position: absolute;
	left: 14px;
	top: 10px;
	height: 20px;
`;

const Group28 = styled.div`
	width: 381px;
	height: 82px;
	position: absolute;
	left: 1010px;
	top: 454px;
`;

const EnterPasswordHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 211px;
	min-height: 20px;
	position: absolute;
	left: 14px;
	top: 10px;
	height: 20px;
`;

const StayLoggedIn = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 211px;
	min-height: 20px;
	position: absolute;
	left: 33px;
	top: 62px;
	height: 20px;
`;

const Rectangle19 = styled.div`
	width: 12px;
	height: 12px;
	background: linear-gradient(-90deg, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2)), rgb(149, 149, 149);
	background-repeat: no-repeat, no-repeat;
	background-size: contain, contain;
	background-position: center, center;
	border-radius: 3px;
	position: absolute;
	left: 1024px;
	top: 517px;
`;

const Group26 = styled.div`
	width: 101px;
	height: 31px;
	position: absolute;
	left: 1150px;
	top: 566px;
	cursor: pointer
`;

const Group29 = styled.div`
	width: 101px;
	height: 31px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle18 = styled.div`
	width: 101px;
	height: 31px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 65px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Login = styled.span`
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 36px;
	min-height: 18px;
	position: absolute;
	left: 32px;
	top: 7px;
	height: 18px;
`;

const IForgotMyPassword = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 145px;
	min-height: 17px;
	position: absolute;
	left: 1131px;
	top: 615px;
	height: 17px;
`;

const DonTHaveAnAccountSignUp = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 220px;
	min-height: 17px;
	position: absolute;
	left: 1095px;
	top: 652px;
	height: 17px;
`;

