import React from "react";
import styled from "@emotion/styled";
/**
 * `<OwnerHomepage>` ('Owner homepage')
 * - [Open in Figma](https://figma.com/file/WEOugNKOtO6S4Asy1vQnRs?node-id=1:2)
 * - [Open in Grida](https://code.grida.co/files/WEOugNKOtO6S4Asy1vQnRs?node=1:2)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <OwnerHomepage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/454bc613-6df2-4ef0-8562-70657f94630c)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://WEOugNKOtO6S4Asy1vQnRs/1:2 -->
 */
export function OwnerHomepage() {
  return (
    <RootWrapperOwnerHomepage>
      <Text>
        <br/>

      </Text>
      <Frame22>
        <Rectangle1/>
        <CloudCar>
          CloudCar
        </CloudCar>
        <Group15>
          <Rectangle5/>
          <HowItWorks>
            How it works<br/>

          </HowItWorks>
        </Group15>
        <Group16>
          <Rectangle6/>
          <Locations>
            Locations
          </Locations>
        </Group16>
        <Group17>
          <Rectangle7/>
          <AboutUs>
            About Us
          </AboutUs>
        </Group17>
        <Group18>
          <Rectangle8/>
          <Notifications>
            Notifications<br/>

          </Notifications>
        </Group18>
        <Rectangle12/>
        <Group20>
          <Group5>
            <Rectangle11/>
          </Group5>
          <Group9>
            <User1/>
            <LogIn>
              Log in<br/>

            </LogIn>
          </Group9>
          <Frame7>
            <Group20_0001>
              <Group5_0001>
                <Rectangle11_0001/>
              </Group5_0001>
              <Group9_0001>
                <User1_0001/>
                <ViewMyProfile>
                  View my profile<br/>
<br/>

                </ViewMyProfile>
              </Group9_0001>
            </Group20_0001>
            <Screenshot20240221At3481/>
          </Frame7>
        </Group20>
        <Ellipse3/>
        <VecteezyCarHeadlightAndIsolatedOnBlack21181671/>
        <UnlockThePotentialOfYourIdleCar>
          Unlock the potential of your idle car!
        </UnlockThePotentialOfYourIdleCar>
        <RentItOutAndEarnFromHomeHassleFree>
          Rent it out and earn from home, hassle-free.
        </RentItOutAndEarnFromHomeHassleFree>
        {/* <Group57>
          <Rectangle25/>
          <AbdulAhadHasBookedAudiA5From14022024Till15022024>
            Abdul Ahad has booked Audi A5<br/>
from 14/02/2024 till 15/02/2024
          </AbdulAhadHasBookedAudiA5From14022024Till15022024>
          <_0732Pm>
            07:32 PM
          </_0732Pm>
          <_0340Pm>
            03:40 PM
          </_0340Pm>
          <Line7/>
          <Line8/>
          <Line9/>
          <UmerJamilAddedAReview>
            Umer Jamil added a review
          </UmerJamilAddedAReview>
          <ViewAll>
            View all
          </ViewAll>
          <ViewDetails>
            View details
          </ViewDetails>
          <ViewDetails_0001>
            View details
          </ViewDetails_0001>
        </Group57> */}
        <Frame8>
          <Group20_0001>
            <Group5_0001>
              <Rectangle11_0001/>
            </Group5_0001>
          </Group20_0001>
          <Group5_0003>
            <Rectangle11_0003/>
          </Group5_0003>
          <Group9_0002 onClick={()=>{window.location.href = "/renterform"}}>
            <ListACar>
              List a car
            </ListACar>
          </Group9_0002>
        </Frame8>
        <Frame9>
          <Group20_0001>
            <Group5_0001>
              <Rectangle11_0001/>
            </Group5_0001>
          </Group20_0001>
          <Group5_0003>
            <Rectangle11_0003/>
          </Group5_0003>
          <Group9_0003>
            <ViewBookings>
              View Bookings<br/>

            </ViewBookings>
          </Group9_0003>
        </Frame9>
        <Frame10>
          <Group20_0001>
            <Group5_0001>
              <Rectangle11_0001/>
            </Group5_0001>
          </Group20_0001>
          <Group5_0007>
            <Rectangle11_0007/>
          </Group5_0007>
          <Group9_0004>
            <Inbox>
              Inbox
            </Inbox>
          </Group9_0004>
        </Frame10>
      </Frame22>
    </RootWrapperOwnerHomepage>
  )
}

const RootWrapperOwnerHomepage = styled.div`
	min-height: 100vh;
	min-width: 100vw;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const Text = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 69px;
	min-height: 21px;
	position: absolute;
	left: 1285px;
	top: calc((calc((50% + -386px)) - 11px));
	height: 21px;
`;

const Frame22 = styled.div`
	width: 100vw;
	height: 100vh;
	position: relative;
	left: 0px;
	top: 0px;
`;

const Rectangle1 = styled.div`
	width: 100vw;
	height: 10vh;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const CloudCar = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 114px;
	min-height: 32px;
	position: relative;
	left: 136px;
	top: 15px;
	height: 32px;
`;

const Group15 = styled.div`
	width: 250px;
	height: 37px;
	position: absolute;
	left: 256px;
	top: 13px;
`;

const Rectangle5 = styled.div`
	width: 138px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const HowItWorks = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 120px;
	min-height: 17px;
	position: absolute;
	left: 27px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group16 = styled.div`
	width: 118px;
	height: 37px;
	position: absolute;
	left: 402px;
	top: 13px;
`;

const Rectangle6 = styled.div`
	width: 118px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Locations = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 62px;
	min-height: 17px;
	position: absolute;
	left: 28px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group17 = styled.div`
	width: 86px;
	height: 37px;
	position: absolute;
	left: 528px;
	top: 13px;
`;

const Rectangle7 = styled.div`
	width: 100px;
	height: 40px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const AboutUs = styled.span`
	color: black;
	text-overflow: ellipsis;
	
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 70px;
	min-height: 17px;
	position: absolute;
	left: 26px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group18 = styled.div`
	width: 130px;
	height: 37px;
	position: absolute;
	left: 622px;
	top: 13px;
`;

const Rectangle8 = styled.div`
	width: 98px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Notifications = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 93px;
	min-height: 17px;
	position: absolute;
	left: 37px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Rectangle12 = styled.div`
	width: 100vw;
	height: 100vh;
	background: linear-gradient(-180deg, rgb(26, 44, 46), black);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 64px;
`;

const Group20 = styled.div`
	width: 214px;
	height: 37px;
	position: absolute;
	left: 1071px;
	top: 11px;
`;

const Group5 = styled.div`
	width: 214px;
	height: 37px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle11 = styled.div`
	width: 214px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9 = styled.div`
	width: 113px;
	height: 17px;
	position: absolute;
	left: 51px;
	top: 10px;
`;

const User1 = styled.div`
	width: 27px;
	height: 16px;
	background: url(https://s3-alpha-sig.figma.com/img/b0bf/c795/ba787cb4b4e8b0ab0700c27e53aff8a7?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=GhNqxZRY84eqhw4Q9-iJOv12-Ih7GNW06B3C5XZkoEOg41NEsTEwy37M1G2CYagRqhLd7pg2BrhEDnZPNy3RANHW-pUdvMR7nCiIIG4o593u7Q5LEuavhDhGqEm7zYh2T4kGqEqHCSyjoM9aTq0a2vPr66W6x2rUpoR8Gu5gUMfa1svl-8K9pQSeHvwPMVgsznT~DX04rDSvxOsiXoULp0kGBw501nDWT9BQtcSd7jKSeWYht22U6Pk~dHMhEOvns-SspOz4Rh2F34oUuv4NLrWCmcVA6QJygCvamgufFYB-8S1ho6wVX74pBRxfptY~47IY83HiRz8BTHPhBe8xAg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 1px;
`;

const LogIn = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 84px;
	min-height: 17px;
	position: absolute;
	left: 35px;
	top: calc((calc((50% + -0px)) - 9px));
	height: 17px;
`;

const Frame7 = styled.div`
	width: 214px;
	height: 37px;
	position: absolute;
	left: 20px;
	top: calc((calc((50% + 0px)) - 19px));
`;

const Group20_0001 = styled.div`
	width: 200px;
	height: 37px;
	position: absolute;
	left: 18px;
	top: 0px;
`;

const Group5_0001 = styled.div`
	width: 200px;
	height: 37px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle11_0001 = styled.div`
	width: 200px;
	height: 37px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9_0001 = styled.div`
	width: 146px;
	height: 17px;
	position: absolute;
	left: 16px;
	top: 8px;
`;

const User1_0001 = styled.div`
	width: 16px;
	height: 16px;
	background: url(https://s3-alpha-sig.figma.com/img/b0bf/c795/ba787cb4b4e8b0ab0700c27e53aff8a7?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=GhNqxZRY84eqhw4Q9-iJOv12-Ih7GNW06B3C5XZkoEOg41NEsTEwy37M1G2CYagRqhLd7pg2BrhEDnZPNy3RANHW-pUdvMR7nCiIIG4o593u7Q5LEuavhDhGqEm7zYh2T4kGqEqHCSyjoM9aTq0a2vPr66W6x2rUpoR8Gu5gUMfa1svl-8K9pQSeHvwPMVgsznT~DX04rDSvxOsiXoULp0kGBw501nDWT9BQtcSd7jKSeWYht22U6Pk~dHMhEOvns-SspOz4Rh2F34oUuv4NLrWCmcVA6QJygCvamgufFYB-8S1ho6wVX74pBRxfptY~47IY83HiRz8BTHPhBe8xAg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 1px;
`;

const ViewMyProfile = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 13px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 131px;
	min-height: 17px;
	position: absolute;
	left: 21px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Screenshot20240221At3481 = styled.div`
	width: 30px;
	height: 30px;
	background: url(https://s3-alpha-sig.figma.com/img/c594/a9dd/7ad818172e8baf59397322cf84240a1e?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=UCdBM43C4aRS1cLB4LBUs4Y9uHNpYC3TwpU2X4tKrJuQ4dTqviD~Nx4hUzP50DrIcqsalD5Tc8hSgyTkJtLabu5NC6ulXCaOBfck8Rf8tq9ekQrePWL6JQdmnNL1NCS4icLekSkzn2W0ywn9Q9c9SoOlz~-yJjVrz~x3mNV6D6ful9~3zQs0lztXE8Ep6FppJ4DT4~qR3BjXPQ6q8oM70X8tnYZAOP-Qw6ZRtHZMZC~mtosQ~R-Tc3Y-H3oFJzXPEBWX73sNlNGhHaSp7jvpysxR2tjsqNvLtRtNQZ4eVyZ-J-XNRurIwlY-xK1YcInCfyXQSc48rGXjJ7qRu~aWsw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border: solid 1px black;
	border-radius: 100px;
	position: absolute;
	left: 181px;
	top: 3px;
`;

const Ellipse3 = styled.div`
	width: 8px;
	height: 8px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 8px / 8px;
	position: absolute;
	left: 744px;
	top: 19px;
`;

const VecteezyCarHeadlightAndIsolatedOnBlack21181671 = styled.div`
	
	width: 85vw;
	height: 85vh;
	background: url(https://s3-alpha-sig.figma.com/img/a655/fb92/a2d62a1fd313b90a9517ae85950e219b?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=pu5Qp9pnY7MHdiEEj6XWIUeymPGKnGAa9c5jvTgEyTy4ac5~Njl4ce~lQBtdWk0eQlioV8X-WscrOiDI1p0KJdBnq21o6tRS2ngNOUl5OlCp-xj1QBaEgWArUwIiSifFK5tX7CsloWqejN6rzPp0xUDurFm~5mUWL-O7-skqnLfq-B~XZEQSMkgScA6CksDER9LCr82tSoZ8SNckh7V8jH06k0FWGcJt19JMUslqjbSWiT4U~rS89kqHrTei~YR0DSIfnQ~vm~10jP5UGZUhi7Gcv02Z4SD7jQl1EMF3A2TJw-cY~tEV0oeHGMqy9leSX7LVHBjaoo59SqrZYg21Tw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border-radius: 66px;
	position: relative;
	left: calc((calc((50% + 0px)) - 675px));
	top: 15vh;
`;

const UnlockThePotentialOfYourIdleCar = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 50px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 507px;
	min-height: 67px;
	position: absolute;
	left: 149px;
	top: 230px;
	height: 67px;
`;

const RentItOutAndEarnFromHomeHassleFree = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 17px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 442px;
	min-height: 47px;
	position: absolute;
	left: 149px;
	top: 358px;
	height: 47px;
	padding-top : 100px
`;

// const Group57 = styled.div`
// 	width: 281px;
// 	height: 135px;
// 	position: absolute;
// 	left: 656px;
// 	top: 64px;
// `;

const Rectangle25 = styled.div`
	width: 268px;
	height: 127px;
	background: rgb(92, 92, 92);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const AbdulAhadHasBookedAudiA5From14022024Till15022024 = styled.span`
	color: rgb(203, 203, 203);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 241px;
	min-height: 29px;
	position: absolute;
	left: 11px;
	top: 8px;
	height: 29px;
`;

const _0732Pm = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 72px;
	min-height: 23px;
	position: absolute;
	left: 215px;
	top: 8px;
	height: 23px;
`;

const _0340Pm = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 72px;
	min-height: 23px;
	position: absolute;
	left: 214px;
	top: 58px;
	height: 23px;
`;

const Line7 = styled.div`
	width: 241px;
	height: 0px;
	border-top: solid 1px rgb(167, 167, 167);
	position: absolute;
	left: 11px;
	top: 55px;
`;

const Line8 = styled.div`
	width: 241px;
	height: 0px;
	border-top: solid 1px rgb(167, 167, 167);
	position: absolute;
	left: 11px;
	top: 95px;
`;

const Line9 = styled.div`
	width: 39px;
	height: 0px;
	border-top: solid 1px rgb(167, 167, 167);
	position: absolute;
	left: 13px;
	top: 121px;
`;

const UmerJamilAddedAReview = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 153px;
	min-height: 28px;
	position: absolute;
	left: 13px;
	top: 60px;
	height: 28px;
`;

const ViewAll = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 153px;
	min-height: 28px;
	position: absolute;
	left: 13px;
	top: 107px;
	height: 28px;
`;

const ViewDetails = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 153px;
	min-height: 28px;
	position: absolute;
	left: 11px;
	top: 36px;
	height: 28px;
`;

const ViewDetails_0001 = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 153px;
	min-height: 28px;
	position: absolute;
	left: 12px;
	top: 78px;
	height: 28px;
`;

const Frame9 = styled.div`
	width: 10vw;
	height: 10vh;
	position: relative;
	left: 136px;
	top: 0px;
`;

const Frame8 = styled.div`
	width: 10vw;
	height: 8vh;
	position: relative;
	left: 136px;
	top: 0px;
`;

const Group5_0003 = styled.div`
	width: 209px;
	height: 37px;
	position: absolute;
	left: 36px;
	top: 0px;
`;

const Rectangle11_0003 = styled.div`
	width: 209px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9_0002 = styled.div`
	width: 86px;
	height: 17px;
	position: absolute;
	left: 98px;
	top: 6px;
	cursor:pointer;
`;

const ListACar = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 120px;
	min-height: 17px;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group9_0003 = styled.div`
	width: 137px;
	height: 17px;
	position: absolute;
	left: 72px;
	top: 6px;
`;

const ViewBookings = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 170px;
	min-height: 17px;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Frame10 = styled.div`
	width: 10vw;
	height: 10vh;
	position: relative;
	left: 136px;
	top: 0px;
`;

const Group5_0007 = styled.div`
	width: 207px;
	height: 37px;
	position: absolute;
	left: 36px;
	top: 0px;
`;

const Rectangle11_0007 = styled.div`
	width: 207px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9_0004 = styled.div`
	width: 56px;
	height: 17px;
	position: absolute;
	left: 112px;
	top: 6px;
`;

const Inbox = styled.span`
	color: rgb(26, 45, 46);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 56px;
	min-height: 17px;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

