import React from "react";
import styled from "@emotion/styled";
/**
 * `<RenterHomepage>` ('Renter homepage')
 * - [Open in Figma](https://figma.com/file/OKTwofbyHtclu6ojQMhVcq?node-id=1:3)
 * - [Open in Grida](https://code.grida.co/files/OKTwofbyHtclu6ojQMhVcq?node=1:3)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <RenterHomepage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/eee808fb-6fd7-4bcb-a74a-f663a81e2c74)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://OKTwofbyHtclu6ojQMhVcq/1:3 -->
 */
export function RenterHomepage() {





  return (
    <RootWrapperRenterHomepage>
      <Frame23>
        <Rectangle1/>
        <Rectangle1/>
        <CloudCar>
          CloudCar
        </CloudCar>
        <Text>
          <br/>

        </Text>
        <Group15>
          <Rectangle5/>
          <HowItWorks>
            How it works<br/>

          </HowItWorks>
        </Group15>
        <Group16 onClick={()=>{window.location.href = "/ownerhomepage";}}>
          <Rectangle6/>
          <Locations>
            List a Car
          </Locations>
        </Group16>
        <Group17>
          <Rectangle7/>
          <AboutUs>
            About Us
          </AboutUs>
        </Group17>
        <Group18>
          <Rectangle8/>
          <Notifications>
            Notifications<br/>

          </Notifications>
        </Group18>
        <Group18>
          <Rectangle8/>
          <Notifications>
            Notifications<br/>

          </Notifications>
        </Group18>
        <Rectangle12/>
        <Rectangle12/>
        <Group20>
          <Group5>
            <Rectangle11/>
          </Group5>
          <Group9>
            <User1/>
            <LogIn>
              Log in<br/>

            </LogIn>
          </Group9>
          <Frame7>
            <Group20_0001>
              <Group5_0001>
                <Rectangle11_0001/>
              </Group5_0001>
              <Group9_0001>
                <User1_0001/>
                <ViewMyProfile>
                  View my profile<br/>
<br/>

                </ViewMyProfile>
              </Group9_0001>
            </Group20_0001>
            <Screenshot20240221At3481/>
          </Frame7>
        </Group20>
        <Ellipse3/>
        <VecteezyCarHeadlightAndIsolatedOnBlack21181671/>
        <VecteezyCarHeadlightAndIsolatedOnBlack21181671/>
        <_1Bac3C366437931/>
        <_1Bac3C366437931/>
        <New1/>
        <New1/>
        <RentCarsNearYou>
          Rent Cars Near You
        </RentCarsNearYou>
        <ConvenientHourlyAndDailyRentalsInsuranceIncluded>
          Convenient hourly and daily rentals. Insurance included. 
        </ConvenientHourlyAndDailyRentalsInsuranceIncluded>
        <Rectangle16/>
        {/* <SearchByLocationDateOrCarModel>
          Search by location, date or car model
        </SearchByLocationDateOrCarModel> */}
        {/* <Group24>
          <Rectangle15/>
          <Search>
            Search
          </Search>
        </Group24> */}
        {/* <Group20_0002>
          <Group5_0001>
            <Rectangle11_0001/>
          </Group5_0001>
        </Group20_0002> */}
        {/* <Group5_0003>
          <Rectangle11_0003/>
        </Group5_0003> */}
        {/* <Group24>
          <Rectangle11_0003/>
        </Group24> */}
        <Group9_0002>
          <RentACar onClick={()=>{window.location.href = '/availablecars'}}>
            Rent a Car
          </RentACar>
        </Group9_0002>
        {/* <Group24>
          <Inbox>
            Inbox
          </Inbox>
        </Group24> */}
        {/* <Group24>
          <Rectangle25/>
          <WelcomeToCloudCarHappyRenting>
            Welcome to CloudCar, Happy Renting!
          </WelcomeToCloudCarHappyRenting>
          <_0913Pm>
            09:13 PM
          </_0913Pm>
          <Line7/>
          <Line9/>
          <ViewAll>
            View all
          </ViewAll>
          <ViewDetails>
            View details
          </ViewDetails>
        </Group24> */}
        {/* <Group59>
          <Rectangle25/>
          <WelcomeToCloudCarHappyRenting>
            Welcome to CloudCar, Happy Renting!
          </WelcomeToCloudCarHappyRenting>
          <_0913Pm>
            09:13 PM
          </_0913Pm>
          <Line7/>
          <Line9/>
          <ViewAll>
            View all
          </ViewAll>
          <ViewDetails>
            View details
          </ViewDetails>
        </Group59> */}
      </Frame23>
    </RootWrapperRenterHomepage>
  )
}

const RootWrapperRenterHomepage = styled.div`
	min-height: 100vh;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const Frame23 = styled.div`
	width: 1440px;
	height: 1064px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle1 = styled.div`
	width: 1440px;
	height: 64px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const CloudCar = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 114px;
	min-height: 32px;
	position: absolute;
	left: 136px;
	top: calc((calc((50% + -500px)) - 16px));
	height: 32px;
`;

const Text = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 69px;
	min-height: 21px;
	position: absolute;
	left: 1285px;
	top: calc((calc((50% + -502px)) - 11px));
	height: 21px;
`;

const Group15 = styled.div`
	width: 138px;
	height: 37px;
	position: absolute;
	left: 256px;
	top: 13px;
`;

const Rectangle5 = styled.div`
	width: 138px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const HowItWorks = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 89px;
	min-height: 17px;
	position: absolute;
	left: 27px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group16 = styled.div`
	width: 118px;
	height: 37px;
	position: absolute;
	left: 402px;
	top: 13px;
	cursor: pointer;
`;

const Rectangle6 = styled.div`
	width: 118px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Locations = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 80px;
	min-height: 17px;
	position: absolute;
	left: 28px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group17 = styled.div`
	width: 86px;
	height: 37px;
	position: absolute;
	left: 528px;
	top: 13px;
`;

const Rectangle7 = styled.div`
	width: 86px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const AboutUs = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 66px;
	min-height: 17px;
	position: absolute;
	left: 26px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Group18 = styled.div`
	width: 130px;
	height: 37px;
	position: absolute;
	left: 622px;
	top: 13px;
`;

const Rectangle8 = styled.div`
	width: 98px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Notifications = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 93px;
	min-height: 17px;
	position: absolute;
	left: 37px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Rectangle12 = styled.div`
	width: 1440px;
	height: 1000px;
	background: linear-gradient(-180deg, rgb(10, 38, 38), rgb(0, 3, 3));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 64px;
`;

const Group20 = styled.div`
	width: 214px;
	height: 37px;
	position: absolute;
	left: 1071px;
	top: 11px;
`;

const Group5 = styled.div`
	width: 214px;
	height: 37px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle11 = styled.div`
	width: 214px;
	height: 37px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9 = styled.div`
	width: 113px;
	height: 17px;
	position: absolute;
	left: 51px;
	top: 10px;
`;

const User1 = styled.div`
	width: 27px;
	height: 16px;
	background: url(https://s3-alpha-sig.figma.com/img/b0bf/c795/ba787cb4b4e8b0ab0700c27e53aff8a7?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=GhNqxZRY84eqhw4Q9-iJOv12-Ih7GNW06B3C5XZkoEOg41NEsTEwy37M1G2CYagRqhLd7pg2BrhEDnZPNy3RANHW-pUdvMR7nCiIIG4o593u7Q5LEuavhDhGqEm7zYh2T4kGqEqHCSyjoM9aTq0a2vPr66W6x2rUpoR8Gu5gUMfa1svl-8K9pQSeHvwPMVgsznT~DX04rDSvxOsiXoULp0kGBw501nDWT9BQtcSd7jKSeWYht22U6Pk~dHMhEOvns-SspOz4Rh2F34oUuv4NLrWCmcVA6QJygCvamgufFYB-8S1ho6wVX74pBRxfptY~47IY83HiRz8BTHPhBe8xAg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 1px;
`;

const LogIn = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 84px;
	min-height: 17px;
	position: absolute;
	left: 35px;
	top: calc((calc((50% + -0px)) - 9px));
	height: 17px;
`;

const Frame7 = styled.div`
	width: 214px;
	height: 37px;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 19px));
`;

const Group20_0001 = styled.div`
	width: 200px;
	height: 37px;
	position: absolute;
	left: 18px;
	top: 0px;
`;

const Group5_0001 = styled.div`
	width: 200px;
	height: 37px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle11_0001 = styled.div`
	width: 200px;
	height: 37px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9_0001 = styled.div`
	width: 146px;
	height: 17px;
	position: absolute;
	left: 16px;
	top: 8px;
`;

const User1_0001 = styled.div`
	width: 16px;
	height: 16px;
	background: url(https://s3-alpha-sig.figma.com/img/b0bf/c795/ba787cb4b4e8b0ab0700c27e53aff8a7?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=GhNqxZRY84eqhw4Q9-iJOv12-Ih7GNW06B3C5XZkoEOg41NEsTEwy37M1G2CYagRqhLd7pg2BrhEDnZPNy3RANHW-pUdvMR7nCiIIG4o593u7Q5LEuavhDhGqEm7zYh2T4kGqEqHCSyjoM9aTq0a2vPr66W6x2rUpoR8Gu5gUMfa1svl-8K9pQSeHvwPMVgsznT~DX04rDSvxOsiXoULp0kGBw501nDWT9BQtcSd7jKSeWYht22U6Pk~dHMhEOvns-SspOz4Rh2F34oUuv4NLrWCmcVA6QJygCvamgufFYB-8S1ho6wVX74pBRxfptY~47IY83HiRz8BTHPhBe8xAg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 1px;
`;

const ViewMyProfile = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 131px;
	min-height: 17px;
	position: absolute;
	left: 21px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Screenshot20240221At3481 = styled.div`
	width: 30px;
	height: 30px;
	background: url(https://s3-alpha-sig.figma.com/img/c594/a9dd/7ad818172e8baf59397322cf84240a1e?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=UCdBM43C4aRS1cLB4LBUs4Y9uHNpYC3TwpU2X4tKrJuQ4dTqviD~Nx4hUzP50DrIcqsalD5Tc8hSgyTkJtLabu5NC6ulXCaOBfck8Rf8tq9ekQrePWL6JQdmnNL1NCS4icLekSkzn2W0ywn9Q9c9SoOlz~-yJjVrz~x3mNV6D6ful9~3zQs0lztXE8Ep6FppJ4DT4~qR3BjXPQ6q8oM70X8tnYZAOP-Qw6ZRtHZMZC~mtosQ~R-Tc3Y-H3oFJzXPEBWX73sNlNGhHaSp7jvpysxR2tjsqNvLtRtNQZ4eVyZ-J-XNRurIwlY-xK1YcInCfyXQSc48rGXjJ7qRu~aWsw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border: solid 1px black;
	border-radius: 100px;
	position: absolute;
	left: 181px;
	top: 3px;
`;

const Ellipse3 = styled.div`
	width: 8px;
	height: 8px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 8px / 8px;
	position: absolute;
	left: 744px;
	top: 19px;
`;

const VecteezyCarHeadlightAndIsolatedOnBlack21181671 = styled.div`
	width: 1250px;
	height: 540px;
	background: url(https://s3-alpha-sig.figma.com/img/a655/fb92/a2d62a1fd313b90a9517ae85950e219b?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=pu5Qp9pnY7MHdiEEj6XWIUeymPGKnGAa9c5jvTgEyTy4ac5~Njl4ce~lQBtdWk0eQlioV8X-WscrOiDI1p0KJdBnq21o6tRS2ngNOUl5OlCp-xj1QBaEgWArUwIiSifFK5tX7CsloWqejN6rzPp0xUDurFm~5mUWL-O7-skqnLfq-B~XZEQSMkgScA6CksDER9LCr82tSoZ8SNckh7V8jH06k0FWGcJt19JMUslqjbSWiT4U~rS89kqHrTei~YR0DSIfnQ~vm~10jP5UGZUhi7Gcv02Z4SD7jQl1EMF3A2TJw-cY~tEV0oeHGMqy9leSX7LVHBjaoo59SqrZYg21Tw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border-radius: 66px;
	position: absolute;
	left: calc((calc((50% + 0px)) - 625px));
	top: 198px;
`;

const _1Bac3C366437931 = styled.div`
	width: 1250px;
	height: 540px;
	background: url(https://s3-alpha-sig.figma.com/img/88a6/17ad/87c4d275da05a273e8b3b8ce82316f61?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=NWFv6xo0SNvp9s5pAgWKJk4mNB0YDFRPIbCtbPno1jpqIMr9JaPDLuxZ0U2-6478ZQduj9iQAhrT4VuE45YoI3eTxmnEnJiz0uxHmbgMCWPc97ExTARLbh31FTBxzmxH0In7r5qK5k1VQb7V~PN8oCx1-x0h5twEf4ZE~-AVeH9yN35IWQo3WPu2NqAySgGppZNlhOPhSzfOh17yiAwi9PoMd9KM7tYCzy5Ew2TFZQZdlDt2pLEHCOMGY5H8clbjMu-boZPOORzxbYrj9s1LNQAfGJHXbwwSouiWGCKKPnJl6APAGnJ5RcNfMWrcz7xeXvJ~z1698nl1baErGylqCA__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border-radius: 66px;
	position: absolute;
	left: 95px;
	top: 198px;
`;

const New1 = styled.div`
	width: 1250px;
	height: 540px;
	background: url(https://s3-alpha-sig.figma.com/img/3a75/37cf/0f9d6eed59c7444037dd9f64462982d1?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=kSokOBPMts-scp-o0dEW62D41BzHGs8q2vHNc4Mw-RwlNJu-43fsUi98YOHvx6FDTCD0Ftak5TJe-6ZYKVRGEGC~kbepv~tP62qSNnDBygs~~-tCsT5OTqhQUnJIcxnPTExk7fxsRQmBQWve7nM12-imcnuywDQ4434U8lpckXb0HlM5lXTtH46AXhDxfkZziILjM4--AFt2DlFLUNgsGGV9cBvF32US~KVIoeOlpltKtT~Xi-vXbaqT7A6lccEsSJ2uHnLLvm23CSNWbqWQZp4bkBQZ8XW1RuGVE6xiwgmOso7Xm430zhyxOc0S2cweag7IPhL-Ox-Z4KEh9luZSw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border-radius: 66px;
	position: absolute;
	left: 95px;
	top: 198px;
`;

const RentCarsNearYou = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 50px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 458px;
	min-height: 67px;
	position: absolute;
	left: 868px;
	top: 226px;
	height: 67px;
`;

const ConvenientHourlyAndDailyRentalsInsuranceIncluded = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 17px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 442px;
	min-height: 47px;
	position: absolute;
	left: 869px;
	top: 278px;
	height: 47px;
`;

const Rectangle16 = styled.div`
	width: 450px;
	height: 47px;
	background: rgb(35, 35, 35);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
	position: absolute;
	left: 864px;
	top: 325px;
`;

const SearchByLocationDateOrCarModel = styled.span`
	color: rgb(97, 97, 97);
	text-overflow: ellipsis;
	font-size: 15px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 1440px;
	min-height: 24px;
	position: absolute;
	left: 0px;
	top: 0px;
	height: 64px;
`;

const Group24 = styled.div`
	width: 1440px;
	height: 64px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle15 = styled.div`
	width: 95px;
	height: 32px;
	background: rgb(0, 0, 0);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Search = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 19px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 65px;
	min-height: 27px;
	position: absolute;
	left: 15px;
	top: 2px;
	height: 27px;
`;

const Group20_0002 = styled.div`
	width: 1440px;
	height: 64px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group5_0003 = styled.div`
	width: 1440px;
	height: 64px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle11_0003 = styled.div`
	width: 209px;
	height: 38px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 19px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group9_0002 = styled.div`
	width: 1440px;
	height: 64px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const RentACar = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 126px;
	min-height: 17px;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
	cursor: pointer;
`;

const Inbox = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 56px;
	min-height: 17px;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 9px));
	height: 17px;
`;

const Rectangle25 = styled.div`
	width: 268px;
	height: 73px;
	background: rgb(92, 92, 92);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const WelcomeToCloudCarHappyRenting = styled.span`
	color: rgb(203, 203, 203);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 11px;
	top: 8px;
`;

const _0913Pm = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 8px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 72px;
	min-height: 23px;
	position: absolute;
	left: 215px;
	top: 8px;
	height: 23px;
`;

const Line7 = styled.div`
	width: 241px;
	height: 0px;
	border-top: solid 1px rgb(167, 167, 167);
	position: absolute;
	left: 11px;
	top: 44px;
`;

const Line9 = styled.div`
	width: 39px;
	height: 0px;
	border-top: solid 1px rgb(167, 167, 167);
	position: absolute;
	left: 13px;
	top: 62px;
`;

const ViewAll = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 153px;
	min-height: 28px;
	position: absolute;
	left: 13px;
	top: 48px;
	height: 28px;
`;

const ViewDetails = styled.span`
	color: rgb(217, 217, 217);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 153px;
	min-height: 28px;
	position: absolute;
	left: 11px;
	top: 24px;
	height: 28px;
`;

const Group59 = styled.div`
	width: 114px;
	height: 32px;
	position: absolute;
	left: 136px;
	top: calc((calc((50% + -500px)) - 16px));
`;

