import React from "react";
import styled from "@emotion/styled";
/**
 * `<Frame15>` ('Frame 15')
 * - [Open in Figma](https://figma.com/file/asUgXa0tsHsNH105i1oLCa?node-id=65:129)
 * - [Open in Grida](https://code.grida.co/files/asUgXa0tsHsNH105i1oLCa?node=65:129)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Frame15/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5053ba2d-b99c-43a0-958c-0fc7db7995aa)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://asUgXa0tsHsNH105i1oLCa/65:129 -->
 */
export function Frame15({socket}) {

	const [signup_data,setSignupData] = React.useState({
		full_name : "",
		email : "",
		phone_number : "",
		city: "",
		address: "",
		postal_code: "",
		password: "",
		re_enter_password: "",
	})

	function changeSignupData(e) {
		setSignupData({
			...signup_data,
			[e.target.name] : e.target.value
		})
		console.log(signup_data)
	}

	function handleSignup() {
		if(signup_data.password != signup_data.re_enter_password) {
			alert("Password does not match")
			return
		}
		if(signup_data.full_name == "" || signup_data.email == "" || signup_data.phone_number == "" || signup_data.city == "" || signup_data.address == "" || signup_data.postal_code == "" || signup_data.password == "" || signup_data.re_enter_password == "") {
			alert("Please fill all fields")
			return
		}
		socket.emit("signup",signup_data)
	}
	React.useEffect(()=>{
		socket.on("signup",(status)=>{
			if(status == "successfull") {
				alert("Signup Successfull")
			}
			else {
				alert("Signup Failed")
			}
		})
		return ()=>{
			socket.off("signup")
		}
	},[socket])




  return (
    <RootWrapperFrame15>
      <Frame10>
        <CloudCar>
          CloudCar
        </CloudCar>
        <CreateAnAccount>
          Create an account<br/>

        </CreateAnAccount>
        <OwnerDetails>
          Owner details
        </OwnerDetails>
        <Group27/>
        <JohnRodennCastilloDFgm6TlEejyUnsplash1/>
        <FullName>
          Full name
        </FullName>
        <FullName>
          Full name
        </FullName>
        <EnterPassword>
          Enter password
        </EnterPassword>
        <ReEnterPassword>
          Re-enter password<br/>

        </ReEnterPassword>
        <FrontPictureOfCnic>
          Front picture of CNIC<br/>

        </FrontPictureOfCnic>
        <BackPictureOfCnic>
          Back picture of CNIC<br/>

        </BackPictureOfCnic>
        <Email>
          Email
        </Email>
        <PhoneNumber>
          Phone number
        </PhoneNumber>
        <City>
          City
        </City>
        <Address>
          Address<br/>

        </Address>
        <PostalCode>
          Postal Code
        </PostalCode>
        <Group24>
		<input
            type="text"
            placeholder="Enter full name"
            // Add CSS classes for styling
            className="message-input-container"
			name="full_name"
			onChange={changeSignupData}
			value={signup_data.full_name}
            />
        </Group24>
        <Group38>
		<input
            type="text"
            placeholder="Enter password"
            // Add CSS classes for styling
            className="message-input-container"
			name="password"
			onChange={changeSignupData}
			value={signup_data.password}
            />
        </Group38>
        <Group39>
		<input
            type="text"
            placeholder="Re-enter password"
            // Add CSS classes for styling
            className="message-input-container"
			name="re_enter_password"
			onChange={changeSignupData}
			value={signup_data.re_enter_password}
            />
        </Group39>
        <Group29>
		<input
            type="text"
            placeholder="Enter email"
            // Add CSS classes for styling
            className="message-input-container"
			name="email"
			onChange={changeSignupData}
			value={signup_data.email}
            />
        </Group29>
        <Group32>
		  <input
            type="text"
            placeholder="Enter Phone number"
            // Add CSS classes for styling
            className="message-input-container"
			name="phone_number"
			onChange={changeSignupData}
			value={signup_data.phone_number}
            />
        </Group32>
        <Group33>
		<input
            type="text"
            placeholder="Enter city here"
            // Add CSS classes for styling
            className="message-input-container"
			name="city"
			onChange={changeSignupData}
			value={signup_data.city}
            />
        </Group33>
        <Group34>
		<input
            type="text"
            placeholder="Enter password here"
            // Add CSS classes for styling
            className="message-input-container"
			name="address"
			onChange={changeSignupData}
			value={signup_data.address}
            />
        </Group34>
        <Group35>
          <input
            type="text"
            placeholder="Enter postal code"
            // Add CSS classes for styling
            className="message-input-container"
			name="postal_code"
			onChange={changeSignupData}
			value={signup_data.postal_code}
            />
			
        </Group35>
        <Group26>
          <Group29_0001>
            <Rectangle18/>
            <SignUp onClick={handleSignup}>
              Sign up
            </SignUp>
          </Group29_0001>
        </Group26>
        <AlreadyHaveAnAccountSignIn>
          Already have an account? <div style={{cursor:"pointer",}} onClick={()=>{window.location.href = "/login";}}>Sign in</div>
        </AlreadyHaveAnAccountSignIn>
        <Rectangle20 xmlns="http://www.w3.org/2000/svg">
          <path fill="rgba(217, 217, 217, 0)" d="M0 0L8 0L8 2.4L2.4 2.4L2.4 8L0 8L0 0Z"/>
        </Rectangle20>
        <Line2/>
        <Group43>
          <Rectangle22/>
          <Group41>
            <Upload>
              Upload
            </Upload>
            <Group40>
              <Rectangle23 xmlns="http://www.w3.org/2000/svg">
                <path fill="rgba(217, 217, 217, 0)" d="M0 0L8 0L8 2.4L2.4 2.4L2.4 8L0 8L0 0Z"/>
              </Rectangle23>
              <Line3/>
            </Group40>
          </Group41>
        </Group43>
        <Group44>
          <Rectangle23_0001/>
          <Group41>
            <Upload>
              Upload
            </Upload>
            <Group40>
              <Rectangle23 xmlns="http://www.w3.org/2000/svg">
                <path fill="rgba(217, 217, 217, 0)" d="M0 0L8 0L8 2.4L2.4 2.4L2.4 8L0 8L0 0Z"/>
              </Rectangle23>
              <Line3/>
            </Group40>
          </Group41>
        </Group44>
        <ByContinuingYouAgreeToCloudCarSTermsOfUseAndPrivacyPolicy>
          By continuing, you agree to Cloud Car’s Terms of       Use and Privacy Policy.
        </ByContinuingYouAgreeToCloudCarSTermsOfUseAndPrivacyPolicy>
      </Frame10>
    </RootWrapperFrame15>
  )
}

const RootWrapperFrame15 = styled.div`
	min-height: 100vh;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const Frame10 = styled.div`
	width: 1440px;
	height: 832px;
	overflow: hidden;
	background: linear-gradient(-180deg, rgb(26, 44, 46), black);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: calc((calc((50% + 0px)) - 720px));
	top: 0px;
`;

const CloudCar = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 172px;
	min-height: 32px;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
	height: 32px;
`;

const CreateAnAccount = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 188px;
	min-height: 24px;
	position: absolute;
	left: 130px;
	top: 76px;
	height: 24px;
`;

const OwnerDetails = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 123px;
	min-height: 24px;
	position: absolute;
	left: 154px;
	top: 107px;
	height: 24px;
`;

const Group27 = styled.div`
	position: absolute;
	left: 1025px;
	top: 515px;
`;

const JohnRodennCastilloDFgm6TlEejyUnsplash1 = styled.div`
	width: 518px;
	height: 975px;
	background: url(https://s3-alpha-sig.figma.com/img/9e8c/ba92/650f7f0ea16eee826a95c15c872691af?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=hrz7fOexFnqSfxeNwGcs-fwnNj8FN~6t2oms6AYFDTILWt4P5OyZwBSXK~KBW41eT2fhfTiXBkZpxBYjmZ60-NpnnUl6-yX0hzBYQRWDyeWjYVpqjcHD1hfjyyWw5PZAMAxb2NJUtnItyaKtjWZvb-pFPLRlTeuNhzSQ70hBqrDSWp76NehZN9a2piZhhJ2bFkP8uYsjh6K0TF4ZwCNR42Aa9FWnHPHWYxXdGfvBT2PtuvYcmFX-kBSbFTBaaZRiIurS0M4m8VAVnpGm6BONMdm-TrYmA1qCwkyQ3VV1d8ixdAJIHqoy-o7dbmssTeRm00N1cL-5gi331e0470fRtg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border-top-left-radius: 250px;
	border-top-right-radius: 250px;
	position: absolute;
	left: 446px;
	top: 0px;
`;

const FullName = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 83px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 138px;
	height: 18px;
`;

const EnterPassword = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 120px;
	min-height: 18px;
	position: absolute;
	left: 1012px;
	top: 272px;
	height: 18px;
`;

const ReEnterPassword = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 142px;
	min-height: 18px;
	position: absolute;
	left: 1012px;
	top: 347px;
	height: 18px;
`;

const FrontPictureOfCnic = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 198px;
	min-height: 18px;
	position: absolute;
	left: 1014px;
	top: 138px;
	height: 18px;
`;

const BackPictureOfCnic = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 205px;
	min-height: 18px;
	position: absolute;
	left: 1013px;
	top: 204px;
	height: 18px;
`;

const Email = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 44px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 206px;
	height: 18px;
`;

const Username = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 65px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 274px;
	height: 18px;
`;

const Country = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 60px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 342px;
	height: 18px;
`;

const PhoneNumber = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 115px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 416px;
	height: 18px;
`;

const City = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 65px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 490px;
	height: 18px;
`;

const Address = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 72px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 564px;
	height: 18px;
`;

const PostalCode = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 142px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 638px;
	height: 18px;
`;

const Group24 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 159px;
`;

const Rectangle16 = styled.div`
	width: 338px;
	height: 33px;
	background: rgb(96, 89, 89);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const EnterEmailHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 200px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const EnterNameHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 200px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group38 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 998px;
	top: 294px;
`;

const Group39 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 998px;
	top: 368px;
`;

const Group29 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 227px;
`;

const Group30 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 295px;
`;

const EnterUsernameHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 200px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group31 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 363px;
`;

const Pakistan = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 182px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group32 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 437px;
`;

const _92 = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 33px;
	min-height: 17px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 17px;
`;

const Group33 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 511px;
`;

const EnterCityHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 200px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group34 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 585px;
`;

const EnterFullAddressHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 200px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group35 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 659px;
`;

const EnterPostalCodeHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 200px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group26 = styled.div`
	width: 101px;
	height: 31px;
	position: absolute;
	left: 1140px;
	top: 440px;
	cursor: pointer
`;

const Group29_0001 = styled.div`
	width: 101px;
	height: 31px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle18 = styled.div`
	width: 101px;
	height: 31px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 65px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const SignUp = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 71px;
	min-height: 18px;
	position: absolute;
	left: 24px;
	top: 7px;
	height: 18px;
`;

const AlreadyHaveAnAccountSignIn = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 240px;
	min-height: 17px;
	position: absolute;
	left: 1081px;
	top: 529px;
	height: 17px;
`;

const Rectangle20 = styled.svg`
	width: 8px;
	height: 8px;
	position: absolute;
	left: 339px;
	top: 386px;
	transform: rotate(-135deg);
	transform-origin: top left;
`;

const Line2 = styled.div`
	width: 18px;
	height: 0px;
	border-top: solid 1px white;
	position: absolute;
	left: 69px;
	top: 444px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Group43 = styled.div`
	width: 92px;
	height: 27px;
	position: absolute;
	left: 1013px;
	top: 161px;
`;

const Rectangle22 = styled.div`
	width: 92px;
	height: 27px;
	background: linear-gradient(-90deg, rgba(217, 217, 217, 0), rgba(217, 217, 217, 0));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border: solid 1px rgb(167, 167, 167);
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Group41 = styled.div`
	width: 69px;
	height: 17px;
	position: absolute;
	left: 12px;
	top: 5px;
`;

const Upload = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 48px;
	min-height: 17px;
	position: absolute;
	left: 0px;
	top: 0px;
	height: 17px;
`;

const Group40 = styled.div`
	width: 11px;
	height: 13px;
	position: absolute;
	left: 58px;
	top: 1px;
`;

const Rectangle23 = styled.svg`
	width: 8px;
	height: 8px;
	position: absolute;
	left: 6px;
	top: 0px;
	transform: rotate(-315deg);
	transform-origin: top left;
`;

const Line3 = styled.div`
	width: 10px;
	height: 0px;
	border-top: solid 3px rgb(165, 155, 155);
	position: absolute;
	left: 7px;
	top: 13px;
	transform: rotate(-90deg);
	transform-origin: top left;
`;

const Group44 = styled.div`
	width: 92px;
	height: 27px;
	position: absolute;
	left: 1012px;
	top: 227px;
`;

const Rectangle23_0001 = styled.div`
	width: 92px;
	height: 27px;
	background: linear-gradient(-90deg, rgba(217, 217, 217, 0), rgba(217, 217, 217, 0));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border: solid 1px rgb(167, 167, 167);
	border-radius: 10px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const ByContinuingYouAgreeToCloudCarSTermsOfUseAndPrivacyPolicy = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: center;
	width: 241px;
	min-height: 28px;
	position: absolute;
	left: 1070px;
	top: 485px;
	height: 28px;
`;

