import React from "react";
import styled from "@emotion/styled";
/**
 * `<Frame17>` ('Frame 17')
 * - [Open in Figma](https://figma.com/file/oLU9toptuQw6Zhqii0knSN?node-id=6:3)
 * - [Open in Grida](https://code.grida.co/files/oLU9toptuQw6Zhqii0knSN?node=6:3)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Frame17/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8fc12a20-1869-4721-8ebc-a6e863e3efd5)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://oLU9toptuQw6Zhqii0knSN/6:3 -->
 */
export function Frame17() {
  return (
    <RootWrapperFrame17>
      <Frame10>
        <C9A853791730111/>
        <CloudCar>
          CloudCar
        </CloudCar>
        <CreateAnAccount>
          Create an account<br/>

        </CreateAnAccount>
        <RenterDetails>
          Renter details
        </RenterDetails>
        <Group27/>
        <FullName>
          Full name
        </FullName>
        <FullName>
          Full name
        </FullName>
        <EnterPassword>
          Enter password
        </EnterPassword>
        <ReEnterPassword>
          Re-enter password<br/>

        </ReEnterPassword>
        <Email>
          Email
        </Email>
        <Username>
          Username<br/>

        </Username>
        <Country>
          Country<br/>

        </Country>
        <PhoneNumber>
          Phone number
        </PhoneNumber>
        <City>
          City
        </City>
        <Address>
          Address<br/>

        </Address>
        <PostalCode>
          Postal Code
        </PostalCode>
        <Group24>
          <Rectangle16/>
          <EnterEmailHere>
            Enter email here
          </EnterEmailHere>
        </Group24>
        <Group24>
          <Rectangle16/>
          <EnterNameHere>
            Enter name here
          </EnterNameHere>
        </Group24>
        <Group38>
          <Rectangle16/>
          <EnterEmailHere>
            Enter email here
          </EnterEmailHere>
        </Group38>
        <Group39>
          <Rectangle16/>
          <EnterEmailHere>
            Enter email here
          </EnterEmailHere>
        </Group39>
        <Group29>
          <Rectangle16/>
          <EnterEmailHere>
            Enter email here
          </EnterEmailHere>
        </Group29>
        <Group30>
          <Rectangle16/>
          <EnterUsernameHere>
            Enter username here
          </EnterUsernameHere>
        </Group30>
        <Group31>
          <Rectangle16/>
          <Pakistan>
            Pakistan<br/>

          </Pakistan>
        </Group31>
        <Group32>
          <Rectangle16/>
          <_92>
            +92 
          </_92>
        </Group32>
        <Group33>
          <Rectangle16/>
          <EnterCityHere>
            Enter City here
          </EnterCityHere>
        </Group33>
        <Group34>
          <Rectangle16/>
          <EnterEmailHere>
            Enter email here
          </EnterEmailHere>
        </Group34>
        <Group34>
          <Rectangle16/>
          <EnterFullAddressHere>
            Enter full address here
          </EnterFullAddressHere>
        </Group34>
        <Group34>
          <Rectangle16/>
          <EnterPostalCodeHere>
            Enter postal code here
          </EnterPostalCodeHere>
        </Group34>
        <Group34>
          <Group29_0001>
            <Rectangle18/>
            <SignUp>
              Sign up
            </SignUp>
          </Group29_0001>
        </Group34>
        <AlreadyHaveAnAccountSignIn>
          Already have an account? Sign in
        </AlreadyHaveAnAccountSignIn>
        <Rectangle20 xmlns="http://www.w3.org/2000/svg">
          <path fill="rgba(217, 217, 217, 0)" d="M0 0L8 0L8 2.4L2.4 2.4L2.4 8L0 8L0 0Z"/>
        </Rectangle20>
        <Line2/>
        <ByContinuingYouAgreeToCloudCarSTermsOfUseAndPrivacyPolicy>
          By continuing, you agree to Cloud Car’s Terms of       Use and Privacy Policy.
        </ByContinuingYouAgreeToCloudCarSTermsOfUseAndPrivacyPolicy>
        <_1298745GoogleBrandBrandingLogoNetworkIcon1/>
        <_834722FacebookIcon1/>
        <_386655LinkedinLinkedInIcon1/>
      </Frame10>
    </RootWrapperFrame17>
  )
}

const RootWrapperFrame17 = styled.div`
	position: relative;
`;

const Frame10 = styled.div`
	width: 1440px;
	height: 832px;
	overflow: hidden;
	background: linear-gradient(-180deg, black, black);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: calc((calc((50% + 0px)) - 720px));
	top: 0px;
`;

const C9A853791730111 = styled.div`
	width: 819px;
	height: 842px;
	background: url(https://s3-alpha-sig.figma.com/img/d9ae/2975/04718ddb094d18af8f8319bc86157a2c?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=OxrvVqBur8HaGrDLNdjCjNcnvx4ibl1Gyfm6stgd9I5MqS31q443X4tR23HilChEPpD0UFJ-IyCW6Mg8kc7XLgThAZZvOelkIVtsErCX6aR826rcUEw6vza04Mm1LiVNeGlfoEobAqxoLDd7KMWsD0uRHVvVXQvldzrFnQTYerDq6xReBJtRmg~itcoG3LgOtjVXZ1hEr0DDBra7GbmYpWpD96NhPcJl6exOna3T2XvhpFf9Z9XHt~d8yIrgequyRQpCwvYiIKFpvE0yPAiQJdtcvH3h~-oj9RXUvLPRJLYg6IKvq2uqzPrCo61lLxS4uaaLyWAIoJy4uPlaJiB6~Q__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: 244px;
	top: 16px;
`;

const CloudCar = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 172px;
	min-height: 32px;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
	height: 32px;
`;

const CreateAnAccount = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 192px;
	min-height: 24px;
	position: absolute;
	left: 130px;
	top: 76px;
	height: 24px;
`;

const RenterDetails = styled.span`
	color: rgb(57, 168, 161);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 127px;
	min-height: 24px;
	position: absolute;
	left: 163px;
	top: 107px;
	height: 24px;
`;

const Group27 = styled.div`
	position: absolute;
	left: 1025px;
	top: 515px;
`;

const FullName = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 87px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 138px;
	height: 18px;
`;

const EnterPassword = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 124px;
	min-height: 18px;
	position: absolute;
	left: 1009px;
	top: 242px;
	height: 18px;
`;

const ReEnterPassword = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 146px;
	min-height: 18px;
	position: absolute;
	left: 1009px;
	top: 317px;
	height: 18px;
`;

const Email = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 44px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 206px;
	height: 18px;
`;

const Username = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 65px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 274px;
	height: 18px;
`;

const Country = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 60px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 342px;
	height: 18px;
`;

const PhoneNumber = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 119px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 416px;
	height: 18px;
`;

const City = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 65px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 490px;
	height: 18px;
`;

const Address = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 72px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 564px;
	height: 18px;
`;

const PostalCode = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 146px;
	min-height: 18px;
	position: absolute;
	left: 38px;
	top: 638px;
	height: 18px;
`;

const Group24 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 159px;
`;

const Rectangle16 = styled.div`
	width: 338px;
	height: 33px;
	background: rgb(96, 89, 89);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const EnterEmailHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 204px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const EnterNameHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 204px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group38 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 995px;
	top: 264px;
`;

const Group39 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 995px;
	top: 338px;
`;

const Group29 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 227px;
`;

const Group30 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 295px;
`;

const EnterUsernameHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 204px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group31 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 363px;
`;

const Pakistan = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 182px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group32 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 437px;
`;

const _92 = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 35px;
	min-height: 17px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 17px;
`;

const Group33 = styled.div`
	width: 338px;
	height: 33px;
	position: absolute;
	left: 24px;
	top: 511px;
`;

const EnterCityHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 204px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group34 = styled.div`
	width: 819px;
	height: 842px;
	position: absolute;
	left: 244px;
	top: 16px;
`;

const EnterFullAddressHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 204px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const EnterPostalCodeHere = styled.span`
	color: rgb(165, 155, 155);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: left;
	width: 204px;
	min-height: 16px;
	position: absolute;
	left: 12px;
	top: 8px;
	height: 16px;
`;

const Group29_0001 = styled.div`
	width: 101px;
	height: 31px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Rectangle18 = styled.div`
	width: 101px;
	height: 31px;
	background: rgb(57, 168, 161);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 65px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const SignUp = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 75px;
	min-height: 18px;
	position: absolute;
	left: 24px;
	top: 7px;
	height: 18px;
`;

const AlreadyHaveAnAccountSignIn = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Urbanist, sans-serif;
	font-weight: 800;
	text-align: left;
	width: 172px;
	min-height: 17px;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
	height: 32px;
`;

const Rectangle20 = styled.svg`
	width: 8px;
	height: 8px;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
	transform: rotate(-135deg);
	transform-origin: top left;
`;

const Line2 = styled.div`
	width: 172px;
	height: 32px;
	border-top: solid 1px white;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const ByContinuingYouAgreeToCloudCarSTermsOfUseAndPrivacyPolicy = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Urbanist, sans-serif;
	font-weight: 700;
	text-align: center;
	width: 172px;
	min-height: 28px;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
	height: 32px;
`;

const _1298745GoogleBrandBrandingLogoNetworkIcon1 = styled.div`
	width: 172px;
	height: 32px;
	background: url(https://s3-alpha-sig.figma.com/img/9e6c/4d83/73be92daa6b5da9deeb2dd57c99ca69d?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=oAhcK5B~m4Dr-vNF~VxGVSQqB9jz~uHMbrTfMtYe0qr~erC6j3thsFktKEiMmlJXnuWDAy2XsjTKriiTU-ebgDm-~pz5u4Vu6GL2snuyhq5ZB-0nVMFWT3SVik8tNVgJzbuhIB8SZfeNaACjLGIID6CoM3ChDFZesyAhmMp4i4MxqVSZyr9PDi~3q4jgRwEfqsU6cYOb3tGpbL8u8H~mmMpg~GET7lILokctQwGZ3zWAyOlceqKYxSPz~jir4sdQ0dCxTG1AFUUpjSP9ZPnwMdG3gSSUcKVOz0uKjgDYwqT97X9A8zdGXnYRmav-0MUS07W9PqlEyVCjnw78UxJ8Xg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
`;

const _834722FacebookIcon1 = styled.div`
	width: 172px;
	height: 32px;
	background: url(https://s3-alpha-sig.figma.com/img/9716/61ed/7ae8f606140fb669a2e7e048fae23248?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=KYVK-8EV4RFADYNwNHU4mMxlgpRfeamsXkPC2PBTMpH~m4eLhpCGj8RwvccIEoc6GmKCzNrBcjUhhnCqeX8zM-CkU0ssRdeOlN4nsCYP4RQecIY2XebN9JI7V7L4mx-dO2~xohb2ICUDw2agSSo4IaDlaBJjg6wWtFf7cczTheHwgf5u02YYfhM9BJ~inmu-06A8R3bF5~iQqe03bYZwpaVTOgE48bvLINFtDU5pbHPgyV0dLC1cMBMCuZWuxi4zFibo2E-mfLdAtSCvsPfQ4byaz~Qn9Xya9mfGsXIPZnEEgomMMLxuC8C17znd8r80-NYlPWdTnvORzAilW6tYow__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
`;

const _386655LinkedinLinkedInIcon1 = styled.div`
	width: 172px;
	height: 32px;
	background: url(https://s3-alpha-sig.figma.com/img/bdce/f694/2af35970f2eed327232b3eb1980d9f87?Expires=1710115200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=l2VibCUEIVJNx17eLXww0hdgBobolwr80kThWD3izabcNgMHrv~yOgPMsV715ATvldkusxvYjKD0BH1-lkK0Z9ASyglwHoNDE953MCc~fZvQMroIqTHUOy-yRwIvRv0lQYU4o8j6aL67l5sXCVlbB0QN1VgfKQx2b5FKg1lkW6ONbAvZK6I5g-5xW9V8jJHIAXQ2F5vgUqUzXUDOn~IsmIYgPlckhyQLydyTWncowLygOlOt-VhqfS4kcpCydw7sahEu3dvqzxwTRej1kTmBwAdb2pW77wxqDJdhkRDv5Vw~FaKC6t9B0P68mLOK8lhBVKmovwKNQU1VVARIpoynCw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: absolute;
	left: calc((calc((50% + -615px)) - 86px));
	top: calc((calc((50% + -387px)) - 16px));
`;

